package at.technikum.model.card.cardTypes;

public enum CardName {
    Spell,
    RegularSpell,
    Goblin,
    Dragon,
    Wizard,
    Ork,
    Knight,
    Kraken,
    Elf,
    FireGoblin,
    FireDragon,
    FireWizzard,
    FireOrks,
    FireOrk,
    FireKnight,
    FireKraken,
    FireElf,
    FireSpell,
    WaterGoblin,
    WaterDragon,
    WaterWizard,
    WaterOrk,
    WaterKnight,
    WaterKraken,
    WaterElf,
    WaterSpell,
}
