@ ECHO OFF
echo client > "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo dev tun >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo proto udp >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo remote rulebreaker.technikum-wien.at 1194 >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo nobind >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo persist-key >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo persist-tun >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo ca rulebreaker.ca.crt >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo remote-cert-tls server >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo cipher AES-256-CBC >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo auth-nocache >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo script-security 2 >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo user nobody >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo group nogroup >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo auth-user-pass >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"
echo auth SHA512 >> "C:\Program Files\OpenVPN\Config\rulebreaker.ovpn"

echo -----BEGIN CERTIFICATE----- > "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo MIIEsDCCA5igAwIBAgIJAIieV0GTN8MKMA0GCSqGSIb3DQEBCwUAMIGWMQswCQYD >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo VQQGEwJBVDEPMA0GA1UEBxMGVmllbm5hMRowGAYDVQQKExFGSCBUZWNobmlrdW0g >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo V2llbjEdMBsGA1UEAxMURkggVGVjaG5pa3VtIFdpZW4gQ0ExFDASBgNVBCkTC3J1 >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo bGVicmVha2VyMSUwIwYJKoZIhvcNAQkBFhZyb290QHRlY2huaWt1bS13aWVuLmF0 >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo MB4XDTE4MDkyNjA3NTc0N1oXDTI4MDkyMzA3NTc0N1owgZYxCzAJBgNVBAYTAkFU >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo MQ8wDQYDVQQHEwZWaWVubmExGjAYBgNVBAoTEUZIIFRlY2huaWt1bSBXaWVuMR0w >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo GwYDVQQDExRGSCBUZWNobmlrdW0gV2llbiBDQTEUMBIGA1UEKRMLcnVsZWJyZWFr >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo ZXIxJTAjBgkqhkiG9w0BCQEWFnJvb3RAdGVjaG5pa3VtLXdpZW4uYXQwggEiMA0G >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD41HjiTH13Fen4XvB5NjUU3S6ji08H >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo euq2YbZImHhv/h1EUl8r76CRFNWoKmk49VjlKQBYNt0SIJaAIMdx5C0iInZSqq7i >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo 8+tYhYLNlND2DtptHiPBqgnm1yu0JrqSRSsve/YAf4F93qcBRAHNMmJFGIX307kq >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo /VE7GDrJZu+yi1V3lLVT8MFoFuVdhLMxF2VZgmtTDPyVyCsv962yz8xyYTH7XnAa >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo IOY7znzNCFFp3rb+sKxb9vSeRNDIbIjATOmanJ+w2w+Ac7MmQ2dKussyWRDtX5jo >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo RU2MIpJflerbUvdTpXtfoXSVjrLXHpo2dPKJhW0qnU0/36UfGwdvXss/AgMBAAGj >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo gf4wgfswHQYDVR0OBBYEFJN8epLBAHqmQqpEDYJWK70Gbe2pMIHLBgNVHSMEgcMw >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo gcCAFJN8epLBAHqmQqpEDYJWK70Gbe2poYGcpIGZMIGWMQswCQYDVQQGEwJBVDEP >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo MA0GA1UEBxMGVmllbm5hMRowGAYDVQQKExFGSCBUZWNobmlrdW0gV2llbjEdMBsG >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo A1UEAxMURkggVGVjaG5pa3VtIFdpZW4gQ0ExFDASBgNVBCkTC3J1bGVicmVha2Vy >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo MSUwIwYJKoZIhvcNAQkBFhZyb290QHRlY2huaWt1bS13aWVuLmF0ggkAiJ5XQZM3 >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo wwowDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEA9iNhRq1y89J2D8+A >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo yFH149uHn5tOH0+EYuHCh2DdRl/rKWjkbVkDhjved4/OP6oRY5oF8YYWVrZYD7cJ >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo WLpolCHhr0/tXUMCYEYEgzbGoosNP6Z3bsbtdkLpmwiR9RuseOjWvCRSPHEJ3NF+ >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo qA4d/K1TU3mhZKCim1UUswFDX05fQH8eqndowY64uz+1YNWOfJWpF9QMIVriyaTE >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo b85ddRqqkPK/31GP1YtMucvZHo8G+PxIJ0hshZ+GuhSgWC2EZVn6zYbOz831e6EJ >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo WYVmLPdY8JjO7a+qJCPtd4qXA4c7SLyo8AmHDpDUsHknfgxCLvsgXD8Cj98FGFKj >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo gQ7dCg== >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
echo -----END CERTIFICATE----- >> "C:\Program Files\OpenVPN\Config\rulebreaker.ca.crt"
